### ISSUE TITLE
Project's TODO

### ISSUE THREAD

**Issue by gabrieledarrigo** [deborahdelgaudio/bin2dec#1]
Project's TODO

- [ ] Test su bin2dec
- [ ] chalk per colorare l'output
- [ ] Pubblicazione su npm
